platform :ios, '16.0'

target 'GithubUsers' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GithubUsers

  pod 'Alamofire'

  target 'GithubUsersTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GithubUsersUITests' do
    # Pods for testing
  end

end
